nsq_path = "D:\\webx3\\nsq-1.3.0.windows-amd64.go1.21.5\\bin"

[[services]]
name = "nsqlookupd"
command = "nsqlookupd.exe"
args = []
log_file = "nsqlookupd.log"

[[services]]
name = "nsqd"
command = "nsqd.exe"
args = ["--lookupd-tcp-address=127.0.0.1:4160"]
log_file = "nsqd.log"

[[services]]
name = "nsqadmin"
command = "nsqadmin.exe"
args = ["--lookupd-http-address=127.0.0.1:4161"]
log_file = "nsqadmin.log"
