[package]
name = "hook_nsq"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.33", features = ["full"] }
sysinfo = "0.33.0"
tracing = "0.1"
tracing-subscriber = "0.3"
signal-hook = "0.3" # 用于处理系统信号